layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    forks: false
    projects:
    # - repo-name

social_media:
  # behance: your_username
  facebook: taylor.denouden
  # dribbble: your_username
  linkedin: taylor-denouden
  stackoverflow: 2977944
  # twitter: your_username
  # youtube: your_username

topics:
  - name: Computer Vision
    #web_url: https://github.com/topics/css
    #image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png

  - name: Data Visualization

  - name: Natural Language Processing
    #web_url: https://github.com/topics/sass
    #image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/sass/sass.png
