layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    forks: false
    projects:
     - tayden.github.io

social_media:
  # behance: your_username
  facebook: taylor.denouden
  # dribbble: your_username
  linkedin: taylor-denouden
  medium: taylordenouden
  stackoverflow: 2977944
  # twitter: your_username
  # youtube: your_username

topics:
  - name: Deep Style Transfer
    web_url: https://github.com/topics/style-transfer
    #image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png

  - name: Generative Adversarial Networks
    web_url: https://github.com/topics/gan
    
  - name: Natural Language Processing
    web_url: https://github.com/topics/nlp
    #image_url: https://venturebeat.com/wp-content/uploads/2018/09/natural-language-processing.jpg
